### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by diamond-nicholas**
This project involves building a mock Tic Tac Toe game. The main goal is to put into practice the main concepts of Object Oriented Programming, getting user's input, and printing the result to the screen.

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
### Hey there :wave: 
##### Nice attempt at building the user interface for the tic-tact-toe game, however there are some changes to be made as there are requirements for this milestone your need to meet before your project can be approved.
- [ ] `[OPTIONAL]` game asks players for their names.
- [ ] `[REQUIRED]` game tells which player turn it is (without computing who the winner is).
- [ ] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
- [ ] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
#### Remember that you do not need to write logic to achieve this, you just need to mock the basic flow of the game. The logical implementation will come in the next milestone.
##### Submit another review request when you are done making the changes
slack(@ebeagusamuel)

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well in fixing some of the changes required by the previous reviewer.
However, some changes are required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Game should inform a player if the selected move is a draw move (without computing draw). You just have to find a way to inform the player on the occasion of a draw move.
- [ ] Your loop needs to be terminated at some point (after a winning move or draw to be more specific). The snippet below might help:
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello Team, nice work you've done so far in this milestone. However, there are still few missed functionalities you should make before moving on to the next one 🙏😊

<hr>

## **[Mandatory]**

- [x] Could you please make the PR body more descriptive. It helps make it look more professional. Try to describe what you and your partner have accomplished so far in this milestone.
- [ ] As described earlier by previous Code Reviewers you should make your game informs the players the following:-
- [ ] 1- Which player's turn is currently on action! If you don't ask for their names, you should make it by default Player 1 and Player 2
- [ ] 2- When there is an invalid move. For numbers above 9, you should print a message to tell the players that this is an invalid move
- [ ] 3- When there is a win or a draw. You should make your game print messages for a win and a draw situation. (Of course, this is a mockery, so you have to make it stop at some point in your choice and print the winning message and/or draw message)
- [ ] 4- Following the point number 3. Your game needs to tell the player when there is a winning and/or draw move. (Same mockery concept as described above)

<hr>

Kindly make sure to do the mandatory changes before submitting for another re-review 🙏😊

I can see you've implemented a README file on this milestone. GREAT JOB on that 🎉❤

## **[OPTIONAL]**

- You can make your README and your project more professional by taking just 5 mins of your time and upload the app on a live demo link i.e. repl.it for easier access🙏🙏 Feel free to do this optional point after completing the whole app.

<hr>

Good luck and happy coding 👨‍💻💻

**Review by LamiaSristy — APPROVED** [review]
# Status: Approved. 🎉

Hello Team!!!

Your project is now approved. Congratulations on your hard work. 🛠️ 


You can merge the branch now, good luck with your next milestone 🚀.

Feel free to reach me at @lamiasristy 🙋

**Pull request merged**
